### ISSUE TITLE
关于使用上的一些问题

### ISSUE THREAD

**Issue by sayidlibing** [ruchee/vimrc#10]
1：您说的首先确保系统能够找到 ctags，也就是 ctags 添加到了系统的 path 环境变量，是将ctags的文件夹路径加入环境变量么，例如我的是I:\Vim\ctags58
2：无法编译c/cpp，提示C:\windows\system32\cmd.exe /c (g++ -Wall -std=c++14 -o t t.cpp ^&^& t.exe)
cc1plus.exe: error: unrecognized command line option "-std=c++14"
shell returned 1
3：您提到的snippets 补全文件如何下载呢
4：之前我使用过的两个插件蛮不错的， vimtweak（win下的窗口透明工具，我感觉非常实用）， nerdtree（目录树，也很实用）

**Comment by ruchee** [comment]
1、最好是下载一个编译好的吧，ctags官网下载的需要自己编译，已编译好的可以上 ```https://code.google.com/p/unix-cmd-win32/downloads/list```  下载（需要翻Q）
2、这是因为你安装的GCC编译器不是4.9+版本，不支持最新的C++14标准，解决办法：找到_vimrc中所有的c++14，将其改为c++98，Vim命令为 ```:%s/c++14/c++98/g```
3、常用的都在 ```vimfiles/snippets``` 目录下自带了，但都是根据我自己的需要来写的，你不习惯就照着改为适合自己的
4、自己喜欢的插件可以下载来放在 ```vimfiles/bundle``` 目录下，重启 Vim 即可生效

**Comment by sayidlibing** [comment]
十分感谢啊！！
ctags用您所说的地址用红杏翻墙仍旧403啊，囧rz。。
另外，现在还有两个小问题：
1.我仍然喜欢把<c-z><c-a><c-v><c-c>等快捷键分别设置成撤销，全选，复制粘贴等，您的这几个快捷键的配置我不习惯呀。。请问怎么设置呢
2.求教一个关于括号匹配的问题。。。。我这样描述一下吧，_代表指针当前所在位置：
     1) for() {_}
     2) 敲入enter键
     3) for (){
               _
         }

**Comment by ruchee** [comment]
```ctags``` 上这下载吧，我刚传上去的：http://www.ruchee.com/download/ctags.zip

快捷键的设置写在 ```_vimrc``` 文件的后面部分，都有注释，你可以找到不喜欢的改掉，不懂就找资料或照猫画虎即可

最后一点没看明白你说的啥，可加我QQ详聊：1405665177
