### ISSUE TITLE
Ctrl+A, Ctrl+v, Ctrl+s等快捷键的映射在哪里？

### ISSUE THREAD

**Issue by ShengRang** [ruchee/vimrc#11]
我想在插入模式下正常的使用这几个快捷键，应该怎么改？
全选， 复制，粘贴，保存啥的。比底行命令来的快捷

还有相对行号和绝对行号可以弄个快捷键互换一下..比如这样:
function! NumberToggle()
  if(&relativenumber == 1)
    set norelativenumber number
else
    set relativenumber
  endif
endfunc
nnoremap <C-n> :call NumberToggle()<cr>

**Comment by ruchee** [comment]
都有注释，自己看着改吧
