### ISSUE TITLE
airline tab栏出现/x/h/D/之类字符

### ISSUE THREAD

**Issue by 839891627** [ruchee/vimrc#13]
" AirLine             彩色状态栏
let g:airline_theme = 'badwolf'                " 设置主题
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_tabs = 0
" tabline中buffer显示编号
let g:airline#extensions#tabline#buffer_nr_show = 1
"alrLine && PowerLine Config
let g:Powerline_symbols = 'fancy'
let g:airline_powerline_fonts = 1
let Powerline_symbols = 'compatible'
这里然后不会设置了。

![qq 20150827181826](https://cloud.githubusercontent.com/assets/10300651/9518251/057f4088-4ce8-11e5-9775-f42fa04f7084.png)

**Comment by ruchee** [comment]
这个涉及到 airline 的高级设置，这里是字体没有弄好导致的。我没这么配置过，爱莫能助，你可以到 ailine 的代码库去寻求帮助

**Comment by 839891627** [comment]
嗯 好  你的这个配置很好用，大爱啊。
