### ISSUE TITLE
windows 10中文乱码，中文显示出来是方框。

### ISSUE THREAD

**Issue by houzhian** [ruchee/vimrc#14]

**Comment by ruchee** [comment]
为什么关闭了？确定Win10中文乱码吗

**Comment by houzhian** [comment]
您好！我刚看到了之前的一条issue您的回复，windows默认的cmd默认不显示utf-8的中文，以为是这个原因就关闭了，刚才在命令行中打开 gvim test.cpp 依然中文乱码，打开 vim test.cpp 由于都是英文的，所以没有看到乱码。

**Comment by ruchee** [comment]
确实就是cmd对UTF-8支持不好的原因啊，你Win下用最好是使用GUI界面，不要直接在cmd里面用

**Comment by houzhian** [comment]
![8ecb11638673cdce654c3b7de0447068](https://cloud.githubusercontent.com/assets/11814908/12412533/4c74ba6c-bec2-11e5-8e94-18ce198c2aa1.jpg)

直接用GUI也是乱码，在 _vimrc 文件中看到有对各种编码的设置。

**Comment by ruchee** [comment]
这个错误是因为找不到 ctags，你看下安装说明，将 ctags 配置对

**Comment by houzhian** [comment]
![new](https://cloud.githubusercontent.com/assets/11814908/12412659/5b019360-bec3-11e5-8e6c-0c1a618e16b1.jpg)

您看旁边显示的行号，为什么会这样呢？

我就把 ctags.exe 放到 vim74 那个文件夹下边，和 vim.exe 等在同一层级，这样对不？

**Comment by houzhian** [comment]
![new](https://cloud.githubusercontent.com/assets/11814908/12412733/2451459e-bec4-11e5-8689-9bfc64ee059a.jpg)

目前是这样的。

**Comment by ruchee** [comment]
看到了，跟 ctags 没关系。你这种情况我还没遇到过

**Comment by houzhian** [comment]
windows：

Control Panel -> Clock, Language, and Region -> Region -> Administrative -> Language for non-Unicode programs -> Chinese(Simplified,China)

**Comment by ruchee** [comment]
so good

**Comment by baixiaoji** [comment]
你是怎么解决这个问题的？
![image](https://user-images.githubusercontent.com/21168366/29154639-6a29647e-7dc8-11e7-8e88-2c6dae701e04.png)
