### ISSUE TITLE
谢谢你的配置。很清爽。很帅！

### ISSUE THREAD

**Issue by F-Passion** [ruchee/vimrc#19]
嗯。有一些问题。win8上打开gvim后，输入“#include<stdio.h>”后没有语法高亮，“int main(<Right>)”后中间会有奇怪的东西。嗯，它默认不是c语言吧。我是新手，不知道怎么改。打开一个.c或者.cpp后会有语法高亮。还有，默认保存的时候选了.cpp，可是退出后查看，没有后缀。

**Comment by ruchee** [comment]
1. Vim会根据文件后缀来识别是什么语言，如果想手动修改高亮模式，敲这个命令 :se ft=c 或 :set ft=cpp （cpp对应C++语言）
2. Vim保存文件时并不会自动帮你加上文件名后缀

**Comment by F-Passion** [comment]
怎么回复？这样？嗯，我重装了，准备一条一条来配置。谢谢。
