### ISSUE TITLE
更新插件

### ISSUE THREAD

**Issue by bydeath** [ruchee/vimrc#20]
ruchee：
        请问该如何一次性更新所有插件，因为插件目录中并没有.git

**Comment by ruchee** [comment]
我是特意删掉了插件目录的.git，更新都是我手动更新的

如果需要自动更新，你需要选用 Vundle 这样的包管理器

我是更倾向于自己控制全局，所以选择了 Pathogen

**Comment by bydeath** [comment]
嗯嗯，之前vim-html5、vim-markdown总是报错，更新之后好了。我现在装插件用`git submodule add  url path`语句，更新所有插件用`git submodule update --init --recursive`应该可以。插件结构不用变，还是装在bundle目录下面。
