### ISSUE TITLE
新手

### ISSUE THREAD

**Issue by zzilcc** [ruchee/vimrc#23]
我是一个刚刚刚刚接触vim的，是因为被一些IDE编程软件坑了，然后被朋友安利vim，我想问下，
1：我打开了我原有的一个.cpp文件，但是为什么没有语法高亮
2：vim是一个编辑器，要下一个编译器一起用才能编译c++文件么，看到网上有说：Make可以，试了一下不行。我初期只是想用vim来编译运行c++文件
3：插件是在你给的文件中了，还是要自己去下载

**Comment by ruchee** [comment]
1. 如果按说明配置好了的话，按理打开常见编程语言的源文件都会有高亮的，包括.cpp
2. Vim只是一个编辑器，但有插件可以支持在其里面调用外部的编译器编译当前源文件，然后将编译中的报错截取出来，反映在编辑器里面，提示用户哪一行有错。需要安装一个编译器，不需要make，安装GCC或Clang即可
3. 常用插件我都集成好了，具体使用方法看 _vimrc 里面的说明
