### ISSUE TITLE
好像不支持C语言的补全

### ISSUE THREAD

**Issue by wojiushiwolh** [ruchee/vimrc#26]
我想要我输入inclu的时候能通过命令补全变成include，试了好久都没成功，是不支持c还是我没搞出来呀？还望赐教

**Comment by ruchee** [comment]
第一种方式是：在插入模式下键入 in 然后按 Tab 键

第二种方式是：在插入模式下输入 in 或者更多字母，然后按 Ctrl+P，从下拉列表中选择想要的（Ctrl+P 向上翻，Ctrl+N 向下翻）

第一种是利用的 snipMate 插件，具体的补全项可查看 snippets/cpp.snippets 这个文件

第二种是利用的 dict + tags，dict 此配置已经自带了，tags 需要你自己用 ctags 来生成，详见本项目的 readme 文件

**Comment by wojiushiwolh** [comment]
第一种成功了，第二种还不会，慢慢来，谢谢你啦

**Comment by wojiushiwolh** [comment]
还有个问题，我按\rr想编译运行但是出现了一句:/bin/bash找不到命令，shell返回127，这是咋回事呀

**Comment by ruchee** [comment]
那是因为找不到编译器。你需要将 gcc g++ 等可执行文件的路径加入 PATH 环境变量

**Comment by wojiushiwolh** [comment]
原来是这样，我正在学鸟哥的变量那一块呢，谢谢
