### ISSUE TITLE
排版乱

### ISSUE THREAD

**Issue by Peterhaiker** [ruchee/vimrc#27]
`您好，我从网页上复制一段代码贴到vim中后排版就很乱，请问这是配置文件的问题还是啥？
还有一个问题就是你这个配置文件怎么看文件的编码格式呀？还是我只能自己输入:set fileencoding?

**Comment by ruchee** [comment]
编码格式看编辑器右下方状态栏

排版乱了，Normal模式下，按 gg=G 整理下就行了
