### ISSUE TITLE
启动时提示：vim-gitgutter: cannot find git. Please set g:gitgutter_git_executable.

### ISSUE THREAD

**Issue by ourlog** [ruchee/vimrc#29]
启动时提示：vim-gitgutter: cannot find git. Please set g:gitgutter_git_executable.

如何处理。

**Comment by ruchee** [comment]
哦，这是该插件需要 Git 的支持，你安装个 Git，将 git 可执行文件所在的路径加入 PATH 环境变量即可

如果不需要 Git 相关插件，将 vimfiles/bundle 下的 gitgutter 文件夹删掉就行

**Comment by oneinstack** [comment]
明白了，你做的包非常好，只是刚入手vim，还有不少地方不懂。
