### ISSUE TITLE
配色不正常，自己的问题已经解决。

### ISSUE THREAD

**Issue by happyHou** [ruchee/vimrc#30]
Vim版本：80
平台:wind7

![syntax](https://cloud.githubusercontent.com/assets/13503990/18808442/6a6ee24e-8295-11e6-9d14-0763a2b5557b.png)

![20160924202938](https://cloud.githubusercontent.com/assets/13503990/18808462/bfdd1eb2-8295-11e6-93bd-3b28b7e426dd.jpg)

问题描述：
开始启动显示上面的图片，语言的颜色匹配都不正确。求大神帮助？

**Comment by happyHou** [comment]
作者很棒，帮我剩下了大把的时间。如果有sublime的配置，就更好了。

**Comment by ruchee** [comment]
:+1:

**Comment by happyHou** [comment]
:+1: @ruchee
