### ISSUE TITLE
win7 64位 vim80启动时出错:E484

### ISSUE THREAD

**Issue by youanan** [ruchee/vimrc#31]
VIM更新到8.0,尝试更新,配置也全部更新了一次,
结果,启动GVIM时,不停的出现以下错误,没办法编辑操作了:
![image 1](https://cloud.githubusercontent.com/assets/3162912/18812139/0817c2b0-82fd-11e6-8bca-c9df908b680d.png)
请问一下,是怎么一回事,
使用步骤按你说明配置的.

**Comment by ruchee** [comment]
检查下ctags是不是配置好了
