### ISSUE TITLE
ubuntu下backspace不执行删除操作

### ISSUE THREAD

**Issue by ourlog** [ruchee/vimrc#32]
要使用ctrl+backspace才能执行删除。
检查了vimrc文件backspace=2，兼容模式为关闭。
尝试了google检索来的方法——使用语句backspace=indent，eol，start，也不能解决问题。
请教下，这个问题咋解决。

**Comment by ruchee** [comment]
确定下使用的是Vi还是Vim，Ubuntu下预设的是Vi，Vim需要自己用apt-get安装
你描述的这个情况，我没遇到过

**Comment by ourlog** [comment]
我是按照Readme中linux下的安装方法，在ubuntu下安装的。确定是vim。
好奇怪的问题啊，google上的解决方法都是关闭兼容模式，设置backspace=2或者indent，eol，start，
都试了，没效果。

算了，ctrl+backspace将就凑合用，有机会再慢慢研究。

**Comment by ourlog** [comment]
终于解决这个问题了，把下面这行注释掉，就正常了。
 " imap <c-h> <esc>I
奇怪，在windows下很正常。ubuntu下才遇到这个问题。
