### ISSUE TITLE
编辑器延迟

### ISSUE THREAD

**Issue by xinluoxueyuan** [ruchee/vimrc#33]
打开文件后，用 j k 移动光标，按住不松手会有延迟。松手之后会继续移动一段时间。有没有办法解决

**Comment by ruchee** [comment]
光标移动延迟，一般出现在打开的文件体积过大或单行字符串过多时，这个应该是没法解决，除非你电脑性能足够好

所以不要期望在打开大体积文件时能有顺畅的操作体验，也尽量不要尝试用Vim编辑单行字符很多的文件，比如你用Vim去编辑jquery.min.js这样的文件，那体验就不是很好了
