### ISSUE TITLE
代码输入到底部时自动跳到中间的功能时常没反应

### ISSUE THREAD

**Issue by Peterhaiker** [ruchee/vimrc#35]
您好，标题中的那个功能有时候没有反应，反馈一下

**Comment by ruchee** [comment]
“自动跳到中间”？没弄明白你指的是什么情形

**Comment by wojiushiwolh** [comment]
一开始我用您这个的时候，每次我输到了屏幕下方它都会自动上移，让我的输入行不是永远在最底下，这是很好的功能，可是这几天这个功能不管用了，我也不知道为什么

**Comment by ruchee** [comment]
这个我没怎么注意，也没刻意去设置这么个功能

你试试编辑一个较长的文本，在最后一行输入左括号，编辑器应该会给你自动补全右括号，然后你按下回车，此时应该就会出现你所说的自动将编辑之处置中的现象了

`
(你的光标应该在这里，然后回车)
`

**Comment by wojiushiwolh** [comment]
确实如您所说，不过如果可以的话还是希望您以后改进一下，毕竟总是这样也不是很方便，嘻嘻

**Comment by ruchee** [comment]
好的，感谢反馈
