### ISSUE TITLE
加个自动安装脚本吧

### ISSUE THREAD

**Issue by daviddavid97** [ruchee/vimrc#36]
sudo apt-get install vim-gtk exuberant-ctags git
rm -rf ~/.vim ~/.vimrc
git clone https://github.com/ruchee/vimrc.git ~/vimrc
mv ~/vimrc/vimfiles ~/.vim
mv ~/vimrc/_vimrc ~/.vimrc
cd ~
wget  https://github.com/todylu/monaco.ttf/blob/master/monaco.ttf?raw=true
mv monaco.ttf ~/.fonts

**Comment by ruchee** [comment]
你看，你这不就是了嘛？😄
真要写自动安装脚本，需要考虑的情况不止这么简单，我还是愿意使用者自己手动操作，这能知道配置到底是怎么生效的
