### ISSUE TITLE
打开vim时好多错误

### ISSUE THREAD

**Issue by Peterhaiker** [ruchee/vimrc#37]
大神，今天我换了ubuntu32位16.04的，之前64位的没问题，但是这个一打开vim就有好多错误，什么/tmp/下有个文件打不开，还有WIN啥的未定义

**Comment by ruchee** [comment]
这套配置不分 `32`、`64` 啊，你看下是不是 `Vim` 安装得不对，或者是版本太旧了

**Comment by wojiushiwolh** [comment]
我的vim是最新版的，我也不知道是什么原因，之前从没出过问题

**Comment by ruchee** [comment]
我刚在 `Ubuntu 16.04 64bit` 里面试了下，正常工作

`32bit` 的问题你得自己找下原因了，我手头没 `32bit` 的镜像

**Comment by wojiushiwolh** [comment]
好的，麻烦你了
