### ISSUE TITLE
行号随着光标的移动，来回变。

### ISSUE THREAD

**Issue by chinaestone** [ruchee/vimrc#38]
系统win 10 64位

vim版本信息：
`
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul  1 2017 22:02:17)     
MS-Windows 64-bit GUI version 带 OLE 支持      
包含补丁: 1-692         
编译者 appveyor@APPVYR-WIN      
`

行号会随着光标的移动，来回变化。不知道这是bug，还是有意这么配置的。
如果是bug，应该如何固定显示的行号呢？

![qq 20170706202339](https://user-images.githubusercontent.com/5661710/27910754-169aca28-6289-11e7-97a2-24bb0bf51b6f.png)

**Comment by ruchee** [comment]
故意这么设置的
```
本配置默认显示的是相对行号，如不习惯，可注释掉配置中的 set relativenumber 一项，以使用绝对行号
```

**Comment by chinaestone** [comment]
thx，问题已解决。
