### ISSUE TITLE
我这边有报错

### ISSUE THREAD

**Issue by yangzhu6263736** [ruchee/vimrc#39]
处理 /root/.vimrc 时发生错误:
第  702 行:
E117: Unknown function: promptline#slices#vcs_branch
E15: 无效的表达式: {'a'    : [ '\u' ],'b'    : [ '\W' ],'c'    : [ promptline#slices#vcs_branch(), promptline#slices#git_status() ],'warn' : [ promptline#slices#last_exit_code() ]}                                       " 自定义命令行显示
请按 ENTER 或其它命令继续

**Comment by ruchee** [comment]
这行报错有点让人意外，你换个系统试试，自己排查下问题
