### ISSUE TITLE
macvim，保存php文件时弹出来报错

### ISSUE THREAD

**Issue by xinglu1983** [ruchee/vimrc#40]
![d85092d4-3b3d-4969-b342-3a773e15eabc](https://user-images.githubusercontent.com/21194812/30469425-d60497e2-9a22-11e7-9f70-8cf38191ff79.png)

macvim，保存php文件时弹出来这种好像是语法报错的东东，其实php语法没问题，只是好像这个检查语法的功能找不到对象的关联关系，我想问一下，这个是哪个插件起的作用？

**Comment by ruchee** [comment]
`phpcd` 插件，补全代码用的，位置在 `bundle/vim-php-phpcd`

你本机排查下是什么问题，我这边没看到这种报错

**Comment by xinglu1983** [comment]
看来是版本问题，我的php是7，看了phpcd的git，发现了下面这行，加上后果然没问题了哈~谢谢~
![phpcd](https://user-images.githubusercontent.com/21194812/30530685-7b41ebce-9c7b-11e7-8c11-9da72b55a3df.png)
