### ISSUE TITLE
卡死

### ISSUE THREAD

**Issue by Peterhaiker** [ruchee/vimrc#41]
我就像平时一样编辑，然后按esc进入普通模式时就卡死了，怎么按都没反应，只好杀死。而且编辑的文件也消失了。系统为ubuntu 16.04 32位。大佬遇到过这个情况吗

**Comment by wojiushiwolh** [comment]
可能只是我的vim卡死了

**Comment by wojiushiwolh** [comment]
又卡死了，之前用的另外一个从来没卡过，每次都是从插入模式切换回普通模式的时候卡，这在我写了一大堆东西后是非常致命的。我必须杀死然后重新写。反馈里好像没人遇到这个问题……

**Comment by wojiushiwolh** [comment]
我的vim是7.4版本的，我现在装了8.0了，我先用两天看看问题还在不在了

**Comment by ruchee** [comment]
你是在编写什么编程语言的代码时卡死？该编程语言的解释器或编译器什么版本？

**Comment by wojiushiwolh** [comment]
写C程序时，不过今天早上升级为8.0后用了几个小时还没出现问题，可能就是版本太低了

**Comment by ruchee** [comment]
因为默认开启了语法检查，在你保存文件时会自动调用一次编译器，如果你代码比较复杂，有可能会短暂出现假死

如果还是出现卡死的问题，试试将语法检查关闭掉

找到 `let g:syntastic_check_on_open = 1`，改成 `let g:syntastic_check_on_open = 0`

或者找到 `let g:syntastic_mode_map      = { 'mode': 'active', 'passive_filetypes': ['html', 'xhtml'] }`，改成 `let g:syntastic_mode_map      = { 'mode': 'active', 'passive_filetypes': ['html', 'xhtml', 'c', 'cpp'] }`

**Comment by wojiushiwolh** [comment]
今天用了一整天完全没有问题，应该不是代码复杂的问题，昨天其实哪怕写了一点只要切换模式就永久卡死，因为我等了很长时间也没恢复。今天写的比昨天复杂多了完全没问题。当然还是说声谢谢

**Comment by ruchee** [comment]
OK
