### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Peterhaiker** [ruchee/vimrc#42]
大佬您好，我有个小建议：创建新文件时能根据后缀自动帮我们加上必须的文字。比如c代码的#include<stdio.h>和主函数，脚本的#! /bin/bash等

**Comment by ruchee** [comment]
这个功能以前有，后来被我删掉了，写代码写多了就会发现这个功能没什么必要

当然，你可以自己加上这个功能，很简单，比如安装这个插件应该就 OK 了：[https://github.com/aperezdc/vim-template](https://github.com/aperezdc/vim-template)

**Comment by Peterhaiker** [comment]
嘿嘿，原谅我有点懒。谢了哈
