### ISSUE TITLE
更换主题

### ISSUE THREAD

**Issue by huizhang0110** [ruchee/vimrc#43]
原有主题下，下划线`_`偶尔看不见。所以我想更换一下主题，请问如何更改.vimrc文件

**Comment by huizhang0110** [comment]
搞定了
修改colorscheme

**Comment by huizhang0110** [comment]
还有一事请教，我在保存文件的时候:w,总是出现一堆烦人的Error和Warninｇ,请问怎么关掉啊。

**Comment by ruchee** [comment]
本配置会在保存时自动进行语法检查

编辑 `_vimrc`，找到 `let g:syntastic_check_on_open = 1` 改成 `let g:syntastic_check_on_open = 0` 即可
