### ISSUE TITLE
打开python文件报错呢

### ISSUE THREAD

**Issue by Sdlearn** [ruchee/vimrc#44]
https://i.loli.net/2018/02/07/5a7ab8fa66b70.png

**Comment by ruchee** [comment]
根据这报错信息，你安装的 `Vim` 编译时是链接的 `Python 3.5`，所以需要安装一个 `Python 3.5` 的解释器，然后在 `vimrc` 中指定好对应的安装目录

以安装到了 `C:/Python` 目录为例，在 `vimrc` 中这样写：
```vim
set pythonthreedll=C:/Python/python35.dll
set pythonthreehome=C:/Python
```

手头没有 `Windows` 机器，上面只是模糊的描述，你先试下

**Comment by Sdlearn** [comment]
额，我没有装过python3.5，直接安装的Anaconda 它自带的是python3.6，
我写了个test.py，内容如下：
import time
print('hello World')
在用vim打开的时候直接报的这个错误
是需要再重新下个python3.5装上吗

**Comment by ruchee** [comment]
不想麻烦的话，直接将 `bundle/vim-python` 这个目录删掉，因为是这个插件本身需要 `Python` 支持

**Comment by Sdlearn** [comment]
嗯好，感谢
