### ISSUE TITLE
java出现乱码

### ISSUE THREAD

**Issue by Peterhaiker** [ruchee/vimrc#45]
大神，你好。我在编写了一点java代码后，然后javac编译后再打开文件时，在最开始的public class a{后面出现大串乱码，其实后面是没有东西的

**Comment by ruchee** [comment]
什么系统？不推荐用 Vim 写 Java，使用 IntelliJ IDEA 搭配 Vim 插件更佳

**Comment by Peterhaiker** [comment]
ubuntu18.04。现在被vim惯坏了，排斥IDE……。其实我用cat查看内容还是原样显示，不只是在写java时这样，我发现其他有些地方也这样

**Comment by ruchee** [comment]
看下 Vim 有没有报错吧，最好能截个图出来看下

**Comment by ruchee** [comment]
截图

**Comment by penn201500** [comment]
![image](https://user-images.githubusercontent.com/16840448/46945002-47a5d900-d0a6-11e8-9383-f6c113ebee4d.png)

相关topic： https://stackoverflow.com/questions/51129631/vim-8-1-garbage-printing-on-screen

这个可能和楼主说的是一个问题，暂未解决

系统：ubuntu18.04
vim版本信息：
![image](https://user-images.githubusercontent.com/16840448/46945185-bdaa4000-d0a6-11e8-8c78-0d0c60d35e9d.png)

**Comment by ruchee** [comment]
楼上的 `Python` 代码，我在 `Mac` 下用 `Vagrant` 模拟的 `Ubuntu 18.04` 终端，未能重现该现象

所以可能是你所使用的终端问题，试试安装个别的终端软件试试

**Comment by penn201500** [comment]
换Terminator尝试，是一样的情况。。
但，如果不使用zsh，就正常。应该是zsh设置的环境变量的问题

**Comment by penn201500** [comment]
zsh 升级到5.4.2版本，问题解决！ tks！
