### ISSUE TITLE
代码复制的问题

### ISSUE THREAD

**Issue by FlamesCN** [ruchee/vimrc#46]
兄弟，你这配置挺好，非常感谢。有个问题比较头疼，就是我用ssh登陆服务器，从其它地方拷贝代码粘贴到服务器上面的vim时候，换行的缩进问题很大。越靠后的行，缩进越多，有估计都缩进好几行了，无法复制。麻烦解决下这个问题。
       2.还有个问题，这个vim主题能匹配代码的各种颜色吗？为啥我这完全大部分都是白色字体，好像得自己换主题才行。
      3. 还有这airline什么的，你这个字体应该不行吧，得专门打了ryanoasis/nerd-fonts  这个补丁的才能正常显示。
      4.没用Vundle是因为加载的时候时间更长了吗？

**Comment by ruchee** [comment]
1. 粘贴用 \v 命令
2. 服务器上应该装的不是完整的 Vim，或者只是个 Vi，安装完整版就行
3. 字体没研究，这个配置没用那些酷炫的字体配置
4. 历史原因，想自己控制哪些包升级、哪些包不升级
