### ISSUE TITLE
vi查看文件内容的时候显示的行号是乱的，翻页后行号还是从1开始

### ISSUE THREAD

**Issue by KaimingWan** [ruchee/vimrc#48]
![image](https://user-images.githubusercontent.com/4374015/96333830-c58a8980-109e-11eb-8459-b5536882b028.png)

**Comment by ruchee** [comment]
这是正常现象，不是行号乱了，而是当前显示的是“相对行号”。你所在的那一行显示正确的“绝对行号”，朝上或朝下数，都是从1开始的“相对行号”
