### ISSUE TITLE
有考虑迁移一个neovim版本吗？

### ISSUE THREAD

**Issue by yuxiio** [ruchee/vimrc#60]
如题，感觉neovim的小细节比vim好了不少。真的很希望有一个neovim版本。

**Comment by ruchee** [comment]
目前没这个打算。nvim 我试用过两次，喜欢不上来，又用回官方版本了

**Comment by yuxiio** [comment]
好吧，个人喜好。哈哈。行吧，谢谢啦！你的vim配置真的很好用。我老师推荐的。
