### ISSUE TITLE
插件的文档应该怎么查看 

### ISSUE THREAD

**Issue by cstyleyang** [ruchee/vimrc#9]
例如 :help vim-go,不能查看地vim-go插件的文档
另外，golang怎么配置能有自动提示？

**Comment by ruchee** [comment]
看文档直接去 ```vimfiles/bundle/vim-go/doc``` 下看吧

代码补全现在配置有三种：
1. Ctrl + P 缓冲区补全
2. Ctrl + Z omni补全
3. snipMate 片段补全，用 Tab 键触发，补全文件在 ```vimfiles/snippets/go.snippets``` ，你可以自己按需补充完善

由于有 ```gocode``` 插件的存在，所以你在本机安装一个 ```gocode```，并加入 ```path``` 环境变量，这对编写 ```Go``` 代码大为便利

**Comment by cstyleyang** [comment]
感谢回复，而且速度也是超快

在网上找了一下，只要在vim中输入 :call pathogen#helptags()就可以生成文档，
再输入 :help vim-go就可以在VIM中方便的查看文档了

**Comment by cstyleyang** [comment]
感谢回复，而且速度也是超快

在网上找了一下，只要在vim中输入 :call pathogen#helptags()就可以生成文档，
再输入 :help vim-go就可以在VIM中方便的查看文档了

**Comment by cstyleyang** [comment]
感谢回复，而且速度也是超快

在网上找了一下，只要在vim中输入 :call pathogen#helptags()就可以生成文档，
再输入 :help vim-go就可以在VIM中方便的查看文档了

**Comment by cstyleyang** [comment]
感谢回复，而且速度也是超快

在网上找了一下，只要在vim中输入 :call pathogen#helptags()就可以生成文档，
再输入 :help vim-go就可以在VIM中方便的查看文档了

**Comment by ruchee** [comment]
受教。我已经将文档默认加载了，已提交到本远程仓库：```https://github.com/ruchee/vimrc/commit/599e46f14a20b67f0cec153b46262ed23561dc45```
